services:
  postgres:
    image: postgres:16
    container_name: aurum-postgres
    environment:
      POSTGRES_USER: aurum
      POSTGRES_PASSWORD: aurum
      POSTGRES_DB: aurum_dev
    ports:
      - "5432:5432"
    volumes:
      - aurum_pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: aurum-redis
    ports:
      - "6379:6379"

volumes:
  aurum_pgdata: